### ISSUE TITLE
Broken link: NSA Security Configuration Guidance

### ISSUE THREAD

**Issue by MikaelFangel** [decalage2/awesome-security-hardening#100]
The link doesn't work anymore and returns 404.
 * [NSA Security Configuration Guidance](https://apps.nsa.gov/iaarchive/library/ia-guidance/security-configuration/)

**Comment by decalage2** [comment]
It looks like the new URL is https://www.nsa.gov/Press-Room/Cybersecurity-Advisories-Guidance/
