### ISSUE TITLE
cancellation of cipherli.st and ssldecoder.org

### ISSUE THREAD

**Issue by DanielRuf** [decalage2/awesome-security-hardening#2]
See https://raymii.org/s/blog/Cancellation_notice_for_cipherlist_ssldecoder_and_certificatemonitor.html

As alternative solutions I have setup https://cipherlist.daniel-ruf.de and https://ssldecoder.daniel-ruf.de and I plan to manage them for a long time.

**Comment by decalage2** [comment]
Thanks for the heads up, I'll update the links.
