### ISSUE TITLE
Windows -> ACSC - Hardening Microsoft Windows 10... Dead Link

### ISSUE THREAD

**Issue by imonsay** [decalage2/awesome-security-hardening#32]
Windows ->
ACSC - Hardening Microsoft Windows 10, version 1709, Workstations 
(https://www.cyber.gov.au/publications/hardening-microsoft-windows-10-build-1709)

This link returns a 404 page. 

I suggest it be replaced with the latest version from the same source:
Hardening Microsoft Windows 10 version 21H1 Workstations
(https://www.cyber.gov.au/acsc/view-all-content/publications/hardening-microsoft-windows-10-version-21h1-workstations)

**Comment by decalage2** [comment]
Closed by PR #33
