### ISSUE TITLE
Switches -> DISA - Layer 2 Switch SRG the lnik is dead

### ISSUE THREAD

**Issue by SlickNutter** [decalage2/awesome-security-hardening#54]
I can't reach the content this link points to -> http://iasecontent.disa.mil/stigs/zip/U_Layer_2_Switch_V1R3_SRG.zip

**Comment by Harvester57** [comment]
Moved here: https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_Layer_2_Switch_V2R1_SRG.zip
